# Generated by Django 4.0 on 2022-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Assignment', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('Month', models.CharField(default=False, max_length=100)),
                ('Attendance', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Chapter', models.CharField(max_length=200)),
                ('Note', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='student_image')),
                ('Date_of_Birth', models.DateField(default=False)),
                ('Gender', models.CharField(default=False, max_length=100)),
                ('Address', models.TextField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Guardian_Name', models.CharField(max_length=200)),
                ('PhoneNumber1', models.IntegerField()),
                ('PhoneNumber2', models.IntegerField()),
                ('Class', models.CharField(max_length=200)),
                ('Academic_Year', models.IntegerField()),
                ('Area_of_Interest', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='teacher_image')),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=200)),
                ('Address', models.TextField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('Qualification', models.CharField(max_length=200)),
                ('Date_of_joining', models.DateField()),
                ('Subject', models.CharField(max_length=200)),
                ('Class_in_charge', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=200)),
                ('TimeTable', models.FileField(upload_to='')),
            ],
        ),
    ]
