# Generated by Django 4.0 on 2022-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
