# Generated by Django 4.0.4 on 2022-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_photo_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='Assignment',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Attendance',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='Note',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Photo',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='TimeTable',
            field=models.FileField(upload_to='files/'),
        ),
    ]
