# Generated by Django 4.0.4 on 2022-06-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_assignment_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
    ]
